name: CI Build

on:
  push:
    branches:
      - '*develop*'
      - '*master*'
  pull_request:
    branches:
      - '*develop*'
      - '*master*'

jobs:
  cross_build:
    name: Cross-platform build and test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
        shell: bash

      - name: Install CMake (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake
        shell: bash

      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        run: choco install -y cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
        shell: cmd

      - name: Configure, build and run tests (Linux / macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./ci.sh || true
          ./ci.sh
        shell: bash

      - name: Configure, build and run tests (Windows)
        if: runner.os == 'Windows'
        run: .\ci.cmd Release
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            build/hello
            build/unit_tests
            build/Release/hello.exe
            build/Release/unit_tests.exe
