name: Cross-platform CI

on:
  push:
    branches:
      - '*develop*'
      - '*master*'
  pull_request:
    branches:
      - '*develop*'
      - '*master*'

jobs:
  cross_build:
    name: cross_build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install -y cmake
          # ensure choco-installed tools are available in PATH in the same session
          refreshenv || true

      - name: Install CMake (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake

      - name: Make build script executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./ci.sh

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./ci.sh

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: .\ci.bat

      - name: Deploy
        run: |
          echo "Deploy placeholder — replace with real deploy commands or script"
