on:
  push:
    branches:
      - '*develop*'
      - '*master*'
  pull_request:
    branches:
      - '*develop*'
      - '*master*'

name: Continuous Integration

jobs:
  cross_build:
    name: Cross-platform build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
        shell: bash

      - name: Install CMakeLists (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          if ! command -v cmake >/dev/null 2>&1; then
            brew update
            brew install cmake
          else
            echo "CMakeLists already installed"
          fi
        shell: bash

      - name: Install CMakeLists (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) {
            choco install cmake -y
          } else {
            Write-Host "CMakeLists already installed"
          }
        shell: powershell

      - name: Run build script (Linux / macOS)
        if: matrix.os != 'windows-latest'
        run: |
          chmod +x ./ci.sh || true
          ./ci.sh
        shell: bash

      - name: Run build script (Windows)
        if: matrix.os == 'windows-latest'
        run: .\ci.bat
        shell: powershell

      - name: Deploy
        run: |
          echo "Deploy step placeholder — replace with your actual deploy commands"
